### ISSUE TITLE
About type constraint in MNRE

### ISSUE THREAD

**Issue by Changhao-Xiang** [OSU-NLP-Group/MQA-MIE#1]
MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了
`read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？

**Comment by superjamessyx** [comment]
你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip

**Comment by superjamessyx** [comment]
> MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？

你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip

**Comment by Changhao-Xiang** [comment]
> > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> 
> 你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip

你好，我截取了其中一条数据如下：
`{'token': ['CBS', 'Names', 'Amy', 'Reisenbach', 'Head', 'of', 'Current', 'Programs'], 'h': {'name': 'Amy Reisenbach', 'pos': [2, 4]}, 't': {'name': 'CBS', 'pos': [0, 1]}, 'relation': '/per/org/member_of', 'img_id': '17_06_12425.jpg'}`
里面和实体类型相关的部分似乎只有'relation'中的'/per/org'部分，请问是根据这个来判断实体类型的吗？
如果是，对于'relation'为'none'的数据是如何处理的呢？

**Comment by superjamessyx** [comment]
> > > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> > 
> > 
> > 你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip
> 
> 你好，我截取了其中一条数据如下： `{'token': ['CBS', 'Names', 'Amy', 'Reisenbach', 'Head', 'of', 'Current', 'Programs'], 'h': {'name': 'Amy Reisenbach', 'pos': [2, 4]}, 't': {'name': 'CBS', 'pos': [0, 1]}, 'relation': '/per/org/member_of', 'img_id': '17_06_12425.jpg'}` 里面和实体类型相关的部分似乎只有'relation'中的'/per/org'部分，请问是根据这个来判断实体类型的吗？ 如果是，对于'relation'为'none'的数据是如何处理的呢？

嗯嗯是的

**Comment by superjamessyx** [comment]
> > > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> > 
> > 
> > 你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip
> 
> 你好，我截取了其中一条数据如下： `{'token': ['CBS', 'Names', 'Amy', 'Reisenbach', 'Head', 'of', 'Current', 'Programs'], 'h': {'name': 'Amy Reisenbach', 'pos': [2, 4]}, 't': {'name': 'CBS', 'pos': [0, 1]}, 'relation': '/per/org/member_of', 'img_id': '17_06_12425.jpg'}` 里面和实体类型相关的部分似乎只有'relation'中的'/per/org'部分，请问是根据这个来判断实体类型的吗？ 如果是，对于'relation'为'none'的数据是如何处理的呢？

None 的情况我们在代码里有处理  (https://github.com/OSU-NLP-Group/MQA/blob/main/tasks/mre_17.py)，这里的命名实体只是用来限制relation的可能性的。

**Comment by Changhao-Xiang** [comment]
好的，谢谢解答！

**Comment by xf12333** [comment]
> MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？

请问您成功训练起来了吗

**Comment by Changhao-Xiang** [comment]
> > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> 
> 请问您成功训练起来了吗

我只参考了论文中的结果，没有跑过训练代码

**Comment by xf12333** [comment]
> > > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> > 
> > 
> > 请问您成功训练起来了吗
> 
> 我只参考了论文中的结果，没有跑过训练代码
好的，谢谢回复

**Comment by xf12333** [comment]
> > MNRE数据集中好像没有给定实体的类型，看起来在`tasks/read_dataset.py`里的`def get_re_data_type`直接使用了 `read_json('./dataset/mre/mre_v2/txt/test_type.json')`获得实体类型，请问这里的具体实现是怎么样的？
> 
> 你好，这个实体类型，是原始数据集已经提供的。可以参考：https://github.com/thecharm/MNRE/blob/main/Version-1/mnre_txt_org.zip

您好，请问twitter-2015和twitter-2017文件夹中的test.json文件是怎么获得的呢
