### ISSUE TITLE
缺失文件

### ISSUE THREAD

**Issue by xf12333** [OSU-NLP-Group/MQA-MIE#3]
![微信截图_20241016202535](https://github.com/user-attachments/assets/ca15aebf-3d02-4de0-9025-eaf4811245c8)
您好，请问这行代码中的test.json是怎么生成的呢，原数据集里没有这个json文件。

**Comment by drogozhang** [comment]
@superjamessyx It would be great if you can upload these missing files for easier re-implementation of our method :)

**Comment by superjamessyx** [comment]
> ![微信截图_20241016202535](https://private-user-images.githubusercontent.com/87306329/377050111-ca15aebf-3d02-4de0-9025-eaf4811245c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY3MzcsIm5iZiI6MTcyOTY2NjQzNywicGF0aCI6Ii84NzMwNjMyOS8zNzcwNTAxMTEtY2ExNWFlYmYtM2QwMi00ZGUwLTkwMjUtZWFmNDgxMTI0NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzBiMjZmNTBiOTJkNDUwYTI5YmRlODFlMTk3ZjYwYTdkMzdhZmNjYmM1NzVhYjk4OTM2MzA1ODg2ZjZlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICW9Bpezw3ihAXM7ygIsQaGme8X_It0apLX1Q-uEj_Y) 您好，请问这行代码中的test.json是怎么生成的呢，原数据集里没有这个json文件。

hi，缺失的文件已经补上

**Comment by xf12333** [comment]
> > ![微信截图_20241016202535](https://private-user-images.githubusercontent.com/87306329/377050111-ca15aebf-3d02-4de0-9025-eaf4811245c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY3MzcsIm5iZiI6MTcyOTY2NjQzNywicGF0aCI6Ii84NzMwNjMyOS8zNzcwNTAxMTEtY2ExNWFlYmYtM2QwMi00ZGUwLTkwMjUtZWFmNDgxMTI0NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzBiMjZmNTBiOTJkNDUwYTI5YmRlODFlMTk3ZjYwYTdkMzdhZmNjYmM1NzVhYjk4OTM2MzA1ODg2ZjZlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICW9Bpezw3ihAXM7ygIsQaGme8X_It0apLX1Q-uEj_Y) 您好，请问这行代码中的test.json是怎么生成的呢，原数据集里没有这个json文件。
> 
> hi，缺失的文件已经补上

感谢您的解答。似乎mre中的test_type.json和数据集中的图像并不对应，而且twitter-2017中的图像有损坏，能否麻烦您提供一下呢。万分感谢。

**Comment by xf12333** [comment]
> > ![微信截图_20241016202535](https://private-user-images.githubusercontent.com/87306329/377050111-ca15aebf-3d02-4de0-9025-eaf4811245c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY3MzcsIm5iZiI6MTcyOTY2NjQzNywicGF0aCI6Ii84NzMwNjMyOS8zNzcwNTAxMTEtY2ExNWFlYmYtM2QwMi00ZGUwLTkwMjUtZWFmNDgxMTI0NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzBiMjZmNTBiOTJkNDUwYTI5YmRlODFlMTk3ZjYwYTdkMzdhZmNjYmM1NzVhYjk4OTM2MzA1ODg2ZjZlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICW9Bpezw3ihAXM7ygIsQaGme8X_It0apLX1Q-uEj_Y) 您好，请问这行代码中的test.json是怎么生成的呢，原数据集里没有这个json文件。
> 
> hi，缺失的文件已经补上

您好，请问test.json文件是如何构建的呢，请问有对应的代码吗

**Comment by drogozhang** [comment]
暂时没找到，可以先按照txt对应和后面程序需要的json结构构造一下
