### ISSUE TITLE
调错函数

### ISSUE THREAD

**Issue by xf12333** [OSU-NLP-Group/MQA-MIE#4]
![dbf074fcdfca3662fc7ed4599d596b7](https://github.com/user-attachments/assets/c2331d17-6d0c-49b0-874c-6795b6e58673)
![f9727c88657e084d7fba2a1246ab2a8](https://github.com/user-attachments/assets/3feef642-5c37-458a-af30-45eaccdc9f6b)
请问这是循环调用自己了吗

**Comment by drogozhang** [comment]
No

**Comment by drogozhang** [comment]
@superjamessyx It looks like an error to me. if would be great if you can double check when you are available

**Comment by superjamessyx** [comment]
> ![dbf074fcdfca3662fc7ed4599d596b7](https://private-user-images.githubusercontent.com/87306329/378146395-c2331d17-6d0c-49b0-874c-6795b6e58673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY3OTYsIm5iZiI6MTcyOTY2NjQ5NiwicGF0aCI6Ii84NzMwNjMyOS8zNzgxNDYzOTUtYzIzMzFkMTctNmQwYy00OWIwLTg3NGMtNjc5NWI2ZTU4NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjEwNGJiMGM5NzAxYzBhNmQ3ODBmMzIyOTEwZjNlNzVlMGYwN2Q5NjIzYzExY2JmZjhlNTUxMDA3MjAyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qZ4FL_CLjGEKynjavMQPceti-W11MCwEFcayFZO3Szo) ![f9727c88657e084d7fba2a1246ab2a8](https://private-user-images.githubusercontent.com/87306329/378146419-3feef642-5c37-458a-af30-45eaccdc9f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjY3OTYsIm5iZiI6MTcyOTY2NjQ5NiwicGF0aCI6Ii84NzMwNjMyOS8zNzgxNDY0MTktM2ZlZWY2NDItNWMzNy00NThhLWFmMzAtNDVlYWNjZGM5ZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNDJkODAzMjRjOWY3ZDIwNjk5ZTc3OGQ5YTM3N2E0MzRlMzUzODk5NGRjOTczOTllYjVhOWY3YWU4ZGYxMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sRKhqo5xm6LhdLjx3dvQ0relxqEwbYIfMHINTmntS9k) 请问这是循环调用自己了吗

似乎没有问题，这里call_model_engine 赋的call_blip2_engine_df 是从model_utils 里面导入的，可以查看一下model_utils里对于call_blip2_engine_df函数的定义。model utils 的这个函数和下面定义的这个函数的输入也不同，因此不是循环调用。我们后面会重新命名一下函数名字，以免造成误解。
